### ISSUE TITLE
Instructor Feedback - Problem Statement

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [stasRevin/SettleUp#1]
Looks like a solid project idea. You specified the response formats that you will provide. I'm curious what RESTful Uris you will support, for example. List of cities, list of price ranges, list of features, get locations by price range, etc.  These might be documented something like:

HTTP GET http://www.appdomain.com/users
HTTP GET http://www.appdomain.com/users?size=20&page=5
HTTP GET http://www.appdomain.com/users/123
HTTP GET http://www.appdomain.com/users/123/address

**Comment by stasRevin** [comment]
Thank you for the feedback, Paula. We have updated services to provide different response types including corresponding URIs for them, however the nature of our service is to only return a list of cities where median rent for an apartment with specified number of bedrooms is close (+-$50) to the specified rent in order to keep the service focused on target.
